"""Pydantic data contracts."""

from .entities import (
    Application,
    BusinessCriticality,
    CvssSeverity,
    Dependency,
    DependencyType,
    Deployment,
    Exploitability,
    LibraryRef,
    LicenseModel,
    LicenseOutcome,
    LicenseRisk,
    LicenseRule,
    LicenseRules,
    TransitiveEdge,
    Vulnerability,
)
from .findings import (
    RISK_PRECEDENCE,
    AnalysisReport,
    AppRiskReport,
    AttackPath,
    DependencyFinding,
    DependencyLabel,
    GlobalSummary,
    MaintenanceStatus,
    MatchedVulnerability,
    RemediationPlaybook,
    RiskType,
    RiskyDependencyRef,
    Severity,
    TransitiveChild,
    VulnConfidence,
)

__all__ = [
    # entities
    "Application",
    "BusinessCriticality",
    "CvssSeverity",
    "Dependency",
    "DependencyType",
    "Deployment",
    "Exploitability",
    "LibraryRef",
    "LicenseModel",
    "LicenseOutcome",
    "LicenseRisk",
    "LicenseRule",
    "LicenseRules",
    "TransitiveEdge",
    "Vulnerability",
    # findings
    "RISK_PRECEDENCE",
    "AnalysisReport",
    "AppRiskReport",
    "AttackPath",
    "DependencyFinding",
    "DependencyLabel",
    "GlobalSummary",
    "MaintenanceStatus",
    "MatchedVulnerability",
    "RemediationPlaybook",
    "RiskType",
    "RiskyDependencyRef",
    "Severity",
    "TransitiveChild",
    "VulnConfidence",
]
