"""Pydantic data contracts (Section 4 + Section 9.1)."""

from .entities import (
    Application,
    BaseRisk,
    BusinessCriticality,
    CompatibilityRule,
    CvssSeverity,
    Dependency,
    DependencyType,
    Ecosystem,
    Environment,
    LicenseCategory,
    LicenseInfo,
    LicenseOutcome,
    LicenseRule,
    LicenseRules,
    UsageSignal,
    Vulnerability,
)
from .findings import (
    AnalysisReport,
    AppRiskReport,
    AttackPath,
    DependencyFinding,
    DependencyLabel,
    GlobalSummary,
    MaintenanceStatus,
    MatchedVulnerability,
    RemediationPlaybook,
    RiskType,
    RiskyDependencyRef,
    Severity,
)

__all__ = [
    # entities
    "Application",
    "BaseRisk",
    "BusinessCriticality",
    "CompatibilityRule",
    "CvssSeverity",
    "Dependency",
    "DependencyType",
    "Ecosystem",
    "Environment",
    "LicenseCategory",
    "LicenseInfo",
    "LicenseOutcome",
    "LicenseRule",
    "LicenseRules",
    "UsageSignal",
    "Vulnerability",
    # findings
    "AnalysisReport",
    "AppRiskReport",
    "AttackPath",
    "DependencyFinding",
    "DependencyLabel",
    "GlobalSummary",
    "MaintenanceStatus",
    "MatchedVulnerability",
    "RemediationPlaybook",
    "RiskType",
    "RiskyDependencyRef",
    "Severity",
]
